// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJdTgtmY2KMM6YOXxzAMrshH859Sux-X8',
    appId: '1:654805013167:web:371c7b12af9941da8ffa5a',
    messagingSenderId: '654805013167',
    projectId: 'sentinel-d37fb',
    authDomain: 'sentinel-d37fb.firebaseapp.com',
    storageBucket: 'sentinel-d37fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCflQ5pafOXaKM4xDy9Jz89hB12oebWQIE',
    appId: '1:654805013167:android:921bfee1ad92cc0e8ffa5a',
    messagingSenderId: '654805013167',
    projectId: 'sentinel-d37fb',
    storageBucket: 'sentinel-d37fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ2a8U2DNYIuCS1aYLoRzfT-AINzXtmKs',
    appId: '1:654805013167:ios:a0a1b36c7531808d8ffa5a',
    messagingSenderId: '654805013167',
    projectId: 'sentinel-d37fb',
    storageBucket: 'sentinel-d37fb.firebasestorage.app',
    iosBundleId: 'com.example.sentinelApp',
  );
}
